export const pilots_F1 = [
  { id: 1, name: "Max Verstappen", team: "Red Bull Racing" },
  { id: 2, name: "Liam Lawson", team: "Red Bull Racing" },
  { id: 3, name: "Charles Leclerc", team: "Ferrari" },
  { id: 4, name: "Lewis Hamilton", team: "Ferrari" },
  { id: 5, name: "George Russell", team: "Mercedes" },
  { id: 6, name: "Andrea Kimi Antonelli", team: "Mercedes" },
  { id: 7, name: "Lando Norris", team: "McLaren" },
  { id: 8, name: "Oscar Piastri", team: "McLaren" },
  { id: 9, name: "Fernando Alonso", team: "Aston Martin" },
  { id: 10, name: "Lance Stroll", team: "Aston Martin" },
  { id: 11, name: "Pierre Gasly", team: "Alpine" },
  { id: 12, name: "Jack Doohan", team: "Alpine" },
  { id: 13, name: "Alex Albon", team: "Williams" },
  { id: 14, name: "Carlos Sainz", team: "Williams" },
  { id: 15, name: "Yuki Tsunoda", team: "RB" },
  { id: 16, name: "Isack Hadjar", team: "RB" },
  { id: 17, name: "Nico Hulkenberg", team: "Audi" },
  { id: 18, name: "Gabriel Bortoleto", team: "Audi" },
  { id: 19, name: "Esteban Ocon", team: "Haas" },
  { id: 20, name: "Oliver Bearman", team: "Haas" },
];